uploads = []
generated = []

[[outputs]]
id = "L6kVY-VxNGOqb_cThrfON"
uri = "file://project.tar.gz"
type = "unspecified"
title = "HomeVault - Full Mobile App Source"

[[outputs]]
id = "CnCS0Zqafucd3e-UVT4i5"
uri = "file://homevault-app.tar.gz"
type = "unspecified"
title = "HomeVault - Standalone Expo App (npm)"
